In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

In [2]:
X = np.array([
    [0.0, 0.0],
    [0.0, 1.0],
    [1.0, 0.0],
    [1.0, 1.0]
])

y = np.array([0, 0, 0, 1])

model = Sequential([
    Input(shape=(2,)),
    Dense(8, activation='relu'),
    Dense(8, activation='relu'),
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.01),
    loss='binary_crossentropy',
    metrics=['accuracy']
)


In [3]:
history = model.fit(X, y, epochs=50, verbose=0)

In [4]:
loss, accuracy = model.evaluate(X, y, verbose=0)
print(f"\nFinal Loss: {loss:.6f}, Final Accuracy: {accuracy:.6f}")


Final Loss: 0.150176, Final Accuracy: 1.000000


In [5]:
predictions = model.predict(X)
print("\nPredictions (probabilities for NAND):")
print(predictions)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step

Predictions (probabilities for NAND):
[[0.07024317]
 [0.04318659]
 [0.22005664]
 [0.79042023]]

Predicted Classes (0 = AND, 1 = NAND):
[[0]
 [0]
 [0]
 [1]]


In [6]:
predicted_classes = (predictions > 0.5).astype(int)
print("\nPredicted Classes (0 = AND, 1 = NAND):")
print(predicted_classes)


Predicted Classes (0 = AND, 1 = NAND):
[[0]
 [0]
 [0]
 [1]]
